### PR TITLE
Add missing Find method

### LINKED ISSUE #9: Routes needs new method Routes.Find()
Compiling hostrouter currently seems to need the addition of a Routes.Find( method to comply with the chi.Routes interface.:

../../../../go/pkg/mod/github.com/go-chi/hostrouter@v0.2.0/hostrouter.go:12:20: cannot use Routes{} (value of type Routes) as chi.Routes value in variable declaration: Routes does not implement chi.Routes (missing method Find)

### PR DESCRIPTION
**Pull request by johanneswuerbach**
This was added in https://github.com/go-chi/chi/pull/872 and is required to compile with `go-chi/chi` >= `v5.2.0`

Fixes https://github.com/go-chi/hostrouter/issues/9

### CODE REVIEW

**Review by VojtechVitek — APPROVED** [review]
LGTM. Thank you!

**Comment by KempWatson** [comment]
Thanks for fast response, but it seems version number was not bumped?
Also, as an aside, I see https://github.com/go-chi/hostrouter/issues/7 re NotFound handler still open.

**Comment by VojtechVitek** [comment]
@KempWatson v0.3.0 released, thanks.

Is there a PR for #7?

**Comment by KempWatson** [comment]
Thanks! Re #7, I don't think so.
